### ISSUE TITLE
Make failure messages more specific

### ISSUE THREAD

**Issue by lpil** [dockyard/valid_field#10]
When one of the given examples is invalid or valid when it should not be it would be nice if the exact example that failed was given, rather than listing all the ones that have failed.

**Comment by bcardarella** [comment]
@lpil just want to make sure I understand. You're suggesting for the following:

``` elixir
ValidField.assert_valid_field(:email, ["test@example.com", "other@example.com"])
```

that currently the error message is: `** (ExUnit.AssertionError) Expected the following values to be valid for "email": "test@example.com", "other@example.com"`

but you are looking for: `** (ExUnit.AssertionError) Expected the following values to be valid for "email": "other@example.com"`  ?

Assuming `other@example.com` causes the failure

**Comment by lpil** [comment]
Yes, that's the one!

**Comment by bcardarella** [comment]
@lpil cool, I am :+1: on this. Will take a look

**Comment by bcardarella** [comment]
@lpil I recreated the conditions here: https://github.com/dockyard/valid_field/pull/11 but it appears the behavior is already happening. Are you seeing something different?

**Comment by danmcclain** [comment]
I was going to say that it should only be showing the failure cases, not the passing cases

**Comment by lpil** [comment]
Ah, then I must have misunderstood the error message. Thanks all!
