### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by foresttoney** [dockyard/valid_field#24]
Can the version be bumped to include support for Ecto 2.0? I am currently using the master branch as a dependency, but it would be nice to pull from hex.

**Comment by myared** [comment]
Another vote for this issue. Same boat.

**Comment by bcardarella** [comment]
Ecto 2.0 support was added over a year ago: https://github.com/DockYard/valid_field/pull/19

We currently support Ecto 2.1 on master.

**Comment by bcardarella** [comment]
v0.6.0 was just released.
